-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 12:32:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FVEReminderApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FVEReminderApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FVEReminderApp` DEFAULT CHARACTER SET utf8 ;
USE `FVEReminderApp` ;

-- -----------------------------------------------------
-- Table `FVEReminderApp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FVEReminderApp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(20) NOT NULL COMMENT 'Username of the user',
  `pass` VARCHAR(50) NOT NULL,
  `fullname` VARCHAR(50) NULL,
  `privileges` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0-only view FVE installation, 1-add images to installations and, 2-create installations, 3-admin priviliges (create user, change users , add requirted images)',
  `active` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - inactive, cant do anything 1-active',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FVEReminderApp`.`requiredImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FVEReminderApp`.`requiredImages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `min_images` int(11) NOT NULL DEFAULT 1 COMMENT 'Min ammount of required images that should be saved',
  `description` varchar(200) DEFAULT NULL COMMENT 'Detailed description of what photos should be takes as name could be misleading',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idrequiredImages_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FVEReminderApp`.`fveInstalations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FVEReminderApp`.`fveInstalations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL COMMENT 'State region where the FVE is located',
  `address` VARCHAR(200) NULL COMMENT 'Address of the FVE, for better location if the name isnt telling enough',
  `users_id` INT NOT NULL COMMENT 'User with responisbility for this instalation, assigned by admin. By default should be admin, until assigned',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_fveInstalations_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_fveInstalations_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `FVEReminderApp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FVEReminderApp`.`savedImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FVEReminderApp`.`savedImages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fveInstalations_id` INT NOT NULL COMMENT 'which installation is this immage part of',
  `requiredImages_id` INT NOT NULL COMMENT 'Under what type this images fall into',
  `location` VARCHAR(200) NULL,
  `timeAdded` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NULL COMMENT 'filename should be based on installations name and date IDEALLY',
  `HASH` int(11) NOT NULL COMMENT 'SHA-256 hash, to check for image duplicity.',
  `active` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'As delete is disabled for security reasons, the app needs to check if the image should be ignored and deleted from cloud, for example when installer uploads wrong image, so that there isn''t data overclustering',
  `users_id` INT NOT NULL COMMENT 'User that added this image, to check for bad actors',
  PRIMARY KEY (`id`, `fveInstalations_id`, `requiredImages_id`),
  UNIQUE INDEX `idsavedImages_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_savedImages_fveInstalations1_idx` (`fveInstalations_id` ASC) VISIBLE,
  INDEX `fk_savedImages_requiredImages1_idx` (`requiredImages_id` ASC) VISIBLE,
  INDEX `fk_savedImages_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_savedImages_fveInstalations1`
    FOREIGN KEY (`fveInstalations_id`)
    REFERENCES `FVEReminderApp`.`fveInstalations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_savedImages_requiredImages1`
    FOREIGN KEY (`requiredImages_id`)
    REFERENCES `FVEReminderApp`.`requiredImages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_savedImages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `FVEReminderApp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
